spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://localhost:3306/test
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 202778612592-50ncn2r5nocg5e10adck0hpvp09hj7hs.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile